
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  nodeSelector:
    build: jenkins
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: docker-config
        mountPath: /kaniko/.docker
  - name: k8s
    image: alpine/k8s:1.21.12
    imagePullPolicy: Always
    command:
    - cat
    tty: true
  imagePullSecrets:
  - name: myregistrykey
  volumes:
    - name: docker-config
      configMap:
        name: docker-config