export const CategoriesList = [
  {
    title: 'home_cat_Title1',
    img: '/assets/imgs/categories/torism.png'
  },
  {
    title: 'home_cat_Title2',
    img: '/assets/imgs/categories/furinture.png'
  },
  {
    title: 'home_cat_Title3',
    img: '/assets/imgs/categories/carcare.png'
  },
  {
    title: 'home_cat_Title4',
    img: '/assets/imgs/categories/beauty.png'
  },
]


export const tabsData = [
  {
    name: 'New Arrivals',
    products: [1, 2, 3, 4, 5, 6, 7, 8, 9],
  },
  {
    name: 'Most Viewed',
    products: [1, 2, 3, 4, 5, 6, 7, 8, 9],
  },
  {
    name: 'Best Sellers',
    products: [1, 2, 3, 4, 5, 6, 7, 8, 9],
  },
  {
    name: 'Selected Products for You',
    products: [1, 2, 3, 4, 5, 6, 7, 8, 9],
  },
]


export const CataloguesOffersData = [
  {
    title: "Home_Decorations_Discounts_up_to_75",
    warning:"Offer_ends_until_2_2_2023",
    size: "Offer expires 2/2/2023",
    titleBadge: "40_have_bought_it",
    addTagBadge: true,
    id: 1,
    bgColor: "bg-white",
    hoverBgColor: "hover:bg-primary-600",
    hoverTextColor: "hover:text-white",
    hoverBorderColor: "hover:border-transparent",
    textColor: "text-primary-600",
    borderColor: "ring-2 ring-primary-500 ",
    source: "/assets/images/CataloguesOffers/Rectangle-22.jpg",
  },
  {
    title: "Home_Decorations_Discounts_up_to_75",
    warning:"Offer_ends_until_2_2_2023",
    titleBadge: "40_have_bought_it",
    size: "Offer expires 2/2/2023",
    borderColor: "ring-2 ring-primary-500",
    addTagBadge: true,
    id: 2,
    bgColor: "bg-white",
    hoverBgColor: "hover:bg-primary-600",
    hoverTextColor: "hover:text-white",
    hoverBorderColor: "hover:border-transparent",
    textColor: "text-primary-600",
    source: "/assets/images/CataloguesOffers/Rectangle-23.jpg",
  },
  {
    title: "Home_Decorations_Discounts_up_to_75",
    warning:"Offer_ends_until_2_2_2023",
    size: "Offer expires 2/2/2023",
    titleBadge: "40_have_bought_it",
    id: 3,
    bgColor: "bg-white",
    hoverBgColor: "hover:bg-primary-600",
    hoverTextColor: "hover:text-white",
    hoverBorderColor: "hover:border-transparent",
    textColor: "text-primary-600",
    addTagBadge: true,
    borderColor: "ring-2 ring-primary-500",
    source: "/assets/images/CataloguesOffers/Rectangle-20.jpg",
  },
  {
    title: "Home_Decorations_Discounts_up_to_75",
    warning:"Offer_ends_until_2_2_2023",
    size: "Offer expires 2/2/2023",
    titleBadge: "40_have_bought_it",
    id: 4,
    bgColor: "bg-white",
    hoverBgColor: "hover:bg-primary-600",
    hoverTextColor: "hover:text-white",
    hoverBorderColor: "hover:border-transparent",
    textColor: "text-primary-600",
    addTagBadge: true,
    borderColor: "ring-2 ring-primary-500",
    source: "/assets/images/CataloguesOffers/Rectangle-21.jpg",
  },
  {
    title: "Home_Decorations_Discounts_up_to_75",
    warning:"Offer_ends_until_2_2_2023",
    addTagBadge: true,
    size: "Offer expires 2/2/2023",
    borderColor: "ring-2 ring-primary-500 ",
    id: 1,
    bgColor: "bg-white",
    hoverBgColor: "hover:bg-primary-600",
    hoverTextColor: "hover:text-white",
    hoverBorderColor: "hover:border-transparent",
    textColor: "text-primary-600",
    titleBadge: "40_have_bought_it",
    source: "/assets/images/CataloguesOffers/Rectangle-22.jpg",
  },
  {
    title: "Home_Decorations_Discounts_up_to_75",
    warning:"Offer_ends_until_2_2_2023",
    addTagBadge: true,
    size: "Offer expires 2/2/2023",
    borderColor: "ring-2 ring-primary-500",
    id: 2,
    bgColor: "bg-white",
    hoverBgColor: "hover:bg-primary-600",
    hoverTextColor: "hover:text-white",
    hoverBorderColor: "hover:border-transparent",
    textColor: "text-primary-600",
    titleBadge: "40_have_bought_it",
    source: "/assets/images/CataloguesOffers/Rectangle-23.jpg",
  },
  {
    title: "Home_Decorations_Discounts_up_to_75",
    warning:"Offer_ends_until_2_2_2023",
    size: "Offer expires 2/2/2023",
    titleBadge: "40_have_bought_it",
    id: 3,
    bgColor: "bg-white",
    hoverBgColor: "hover:bg-primary-600",
    hoverTextColor: "hover:text-white",
    hoverBorderColor: "hover:border-transparent",
    textColor: "text-primary-600",
    addTagBadge: true,
    borderColor: "ring-2 ring-primary-500",
    source: "/assets/images/CataloguesOffers/Rectangle-20.jpg",
  },
  {
    title: "Home_Decorations_Discounts_up_to_75",
    warning:"Offer_ends_until_2_2_2023",
    size: "Offer expires 2/2/2023",
    titleBadge: "40_have_bought_it",
    id: 4,
    bgColor: "bg-white",
    hoverBgColor: "hover:bg-primary-600",
    hoverTextColor: "hover:text-white",
    hoverBorderColor: "hover:border-transparent",
    textColor: "text-primary-600",
    addTagBadge: true,
    borderColor: "ring-2 ring-primary-500",
    source: "/assets/images/CataloguesOffers/Rectangle-21.jpg",
  },
];

export const AmazingDiscountsOnHomeProductsData = [
  {
    title: "Air_fryer_1400_watts_capacity_1_2_liters",
    warning:"Offer_ends_until_2_2_2023",
    titleBadge: "best_seller",
    class: "customNumber-red",
    num: 1,
    id: 5,
    heightCard: "h-72",
    bgColor: "bg-teal-400",
    hoverBgColor: "hover:bg-sky-600",
    hoverTextColor: "hover:text-white",
    hoverBorderColor: "hover:border-transparent",
    textColor: "text-teal-900",
    haveFav: true,
    addTagBadge: true,
    borderColor: "ring-teal-400",
    source: "/assets/images/AmazingDiscountsOnHomeProducts/airFryer.jpg",
  },
  {
    title: "9liter_pressure_cooker_one_year_warranty",
    warning:"Offer_ends_until_2_2_2023",
    titleBadge: "40_have_bought_it",
    class: "customNumber-black",
    num: 2,
    id: 6,
    heightCard: "h-72",
    bgColor: "bg-white",
    hoverBgColor: "hover:bg-primary-600",
    hoverTextColor: "hover:text-white",
    hoverBorderColor: "hover:border-transparent",
    textColor: "text-primary-600",
    borderColor: "ring-2 ring-primary-500",
    source: "/assets/images/AmazingDiscountsOnHomeProducts/pan.jpg",
  },
  {
    title: "Gray_divan_bed_with_headboard",
    warning:"Offer_ends_until_2_2_2023",
    titleBadge: "40_have_bought_it",
    class: "customNumber-orange",
    num: 3,
    id: 7,
    heightCard: "h-72",
    bgColor: "bg-white",
    hoverBgColor: "hover:bg-primary-600",
    hoverTextColor: "hover:text-white",
    hoverBorderColor: "hover:border-transparent",
    textColor: "text-primary-600",
    borderColor: "ring-2 ring-primary-500",
    addTagBadge: true,
    source: "/assets/images/AmazingDiscountsOnHomeProducts/bed.jpg",
  },
  {
    title: "Soft_towels_60_10_cm_with_the_finest_cotton",
    warning:"Offer_ends_until_2_2_2023",
    titleBadge: "best_seller",
    class: "customNumber-green",
    num: 4,
    id: 8,
    heightCard: "h-72",
    bgColor: "bg-teal-400",
    haveFav: true,
    hoverBgColor: "hover:bg-teal-600",
    hoverTextColor: "hover:text-white",
    hoverBorderColor: "hover:border-transparent",
    textColor: "text-teal-900",
    borderColor: "ring-teal-400",
    source: "/assets/images/AmazingDiscountsOnHomeProducts/towel.jpg",
  },
  {
    title: "Air_fryer_1400_watts_capacity_1_2_liters",
    warning:"Offer_ends_until_2_2_2023",
    titleBadge: "best_seller",
    class: "customNumber-red",
    num: 1,
    id: 5,
    heightCard: "h-72",
    bgColor: "bg-teal-400",
    hoverBgColor: "hover:bg-sky-600",
    hoverTextColor: "hover:text-white",
    hoverBorderColor: "hover:border-transparent",
    textColor: "text-teal-900",
    haveFav: true,
    addTagBadge: true,
    borderColor: "ring-teal-400",
    source: "/assets/images/AmazingDiscountsOnHomeProducts/airFryer.jpg",
  },
  {
    title: "9liter_pressure_cooker_one_year_warranty",
    warning:"Offer_ends_until_2_2_2023",
    titleBadge: "40_have_bought_it",
    class: "customNumber-black",
    num: 2,
    id: 6,
    heightCard: "h-72",
    bgColor: "bg-white",
    hoverBgColor: "hover:bg-primary-600",
    hoverTextColor: "hover:text-white",
    hoverBorderColor: "hover:border-transparent",
    textColor: "text-primary-600",
    borderColor: "ring-2 ring-primary-500",
    source: "/assets/images/AmazingDiscountsOnHomeProducts/pan.jpg",
  },
  {
    title: "Gray_divan_bed_with_headboard",
    warning:"Offer_ends_until_2_2_2023",
    titleBadge: "40_have_bought_it",
    class: "customNumber-orange",
    num: 3,
    id: 7,
    heightCard: "h-72",
    bgColor: "bg-white",
    hoverBgColor: "hover:bg-primary-600",
    hoverTextColor: "hover:text-white",
    hoverBorderColor: "hover:border-transparent",
    textColor: "text-primary-600",
    borderColor: "ring-2 ring-primary-500",
    addTagBadge: true,
    source: "/assets/images/AmazingDiscountsOnHomeProducts/bed.jpg",
  },
  {
    title: "Soft_towels_60_10_cm_with_the_finest_cotton",
    warning:"Offer_ends_until_2_2_2023",
    titleBadge: "best_seller",
    class: "customNumber-green",
    num: 4,
    id: 8,
    heightCard: "h-72",
    bgColor: "bg-teal-400",
    haveFav: true,
    hoverBgColor: "hover:bg-teal-600",
    hoverTextColor: "hover:text-white",
    hoverBorderColor: "hover:border-transparent",
    textColor: "text-teal-900",
    borderColor: "ring-teal-400",
    source: "/assets/images/AmazingDiscountsOnHomeProducts/towel.jpg",
  },
];

export const TheMostImportantCataloguesData = [
  {
    title: "IMG_4985.HEIC",
    class: "customNumber-red",
    num: 1,
    id: 5,
    heightCard: "h-77 pb-5",
    bgColor: "bg-teal-400",
    hoverBgColor: "hover:bg-teal-600",
    hoverTextColor: "hover:text-white",
    hoverBorderColor: "hover:border-transparent",
    textColor: "text-teal-900",
    addTagBadge: true,
    borderColor: "ring-teal-400",
    source: "/assets/images/TheMostImportantCatalogues/Deals.jpg",
  },
  {
    title: "IMG_4985.HEIC",
    class: "customNumber-black",
    num: 2,
    id: 6,
    heightCard: "h-77 pb-5",
    bgColor: "bg-white",
    hoverBgColor: "hover:bg-primary-600",
    hoverTextColor: "hover:text-white",
    hoverBorderColor: "hover:border-transparent",
    textColor: "text-primary-600",
    borderColor: "ring-2 ring-primary-500",
    source: "/assets/images/TheMostImportantCatalogues/Deals.jpg",
  },
  {
    title: "IMG_4985.HEIC",
    class: "customNumber-orange",
    num: 3,
    id: 7,
    heightCard: "h-77 pb-5",
    bgColor: "bg-white",
    hoverBgColor: "hover:bg-primary-600",
    hoverTextColor: "hover:text-white",
    hoverBorderColor: "hover:border-transparent",
    textColor: "text-primary-600",
    borderColor: "ring-2 ring-primary-500",
    addTagBadge: true,
    source: "/assets/images/TheMostImportantCatalogues/Rectangle-33.jpg",
  },
  {
    title: "IMG_4985.HEIC",
    class: "customNumber-green",
    num: 4,
    id: 8,
    heightCard: "h-77 pb-5",
    bgColor: "bg-teal-400",
    hoverBgColor: "hover:bg-teal-600",
    hoverTextColor: "hover:text-white",
    hoverBorderColor: "hover:border-transparent",
    textColor: "text-teal-900",
    borderColor: "ring-teal-400",
    source: "/assets/images/TheMostImportantCatalogues/Rectangle-33.jpg",
  },
  {
    title: "IMG_4985.HEIC",
    class: "customNumber-red",
    num: 1,
    id: 5,
    heightCard: "h-77 pb-5",
    bgColor: "bg-teal-400",
    hoverBgColor: "hover:bg-teal-600",
    hoverTextColor: "hover:text-white",
    hoverBorderColor: "hover:border-transparent",
    textColor: "text-teal-900",
    addTagBadge: true,
    borderColor: "ring-teal-400",
    source: "/assets/images/TheMostImportantCatalogues/Deals.jpg",
  },
  {
    title: "IMG_4985.HEIC",
    class: "customNumber-black",
    num: 2,
    id: 6,
    heightCard: "h-77 pb-5",
    bgColor: "bg-white",
    hoverBgColor: "hover:bg-primary-600",
    hoverTextColor: "hover:text-white",
    hoverBorderColor: "hover:border-transparent",
    textColor: "text-primary-600",
    borderColor: "ring-2 ring-primary-500",
    source: "/assets/images/TheMostImportantCatalogues/Deals.jpg",
  },
  {
    title: "IMG_4985.HEIC",
    class: "customNumber-orange",
    num: 3,
    id: 7,
    heightCard: "h-77 pb-5",
    bgColor: "bg-white",
    hoverBgColor: "hover:bg-primary-600",
    hoverTextColor: "hover:text-white",
    hoverBorderColor: "hover:border-transparent",
    textColor: "text-primary-600",
    borderColor: "ring-2 ring-primary-500",
    addTagBadge: true,
    source: "/assets/images/TheMostImportantCatalogues/Rectangle-33.jpg",
  },
  {
    title: "IMG_4985.HEIC",
    class: "customNumber-green",
    num: 4,
    id: 8,
    heightCard: "h-77 pb-5",
    bgColor: "bg-teal-400",
    hoverBgColor: "hover:bg-teal-600",
    hoverTextColor: "hover:text-white",
    hoverBorderColor: "hover:border-transparent",
    textColor: "text-teal-900",
    borderColor: "ring-teal-400",
    source: "/assets/images/TheMostImportantCatalogues/Rectangle-33.jpg",
  },
];

export const settingsSlick = {
  dots: false,
  infinite: false,
  speed: 500,
  slidesToShow: 4,
  slidesToScroll: 4,
  initialSlide: 0,
  responsive: [
    {
      breakpoint: 1024,
      settings: {
        slidesToShow: 3,
        slidesToScroll: 3,
        infinite: true,
        dots: true,
      },
    },
    {
      breakpoint: 600,
      settings: {
        slidesToShow: 2,
        slidesToScroll: 2,
        initialSlide: 2,
      },
    },
    {
      breakpoint: 480,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
      },
    },
  ],
};
